# Playbook: monitoring.yaml

---
- name: Deploy Node Exporter
  hosts: all
  roles:
    - node_exporter

- name: Deploy monitoring services
  hosts: monitoring 
  roles:
    - prometheus
    - grafana
