# Playbook: monitoring.yaml

---
- name: Deploy Node Exporter
  hosts: all
  remote_user: root
  vars:
    host_arch: arm64
    action: uninstall
  roles:
    - node_exporter

- name: Deploy monitoring services
  hosts: monitoring 
  remote_user: root
  vars:
    host_arch: arm64
    action: uninstall
  roles:
    - prometheus
    - grafana
