# roles/node-exporter/defaults/main.yaml

host_arch: amd64
action: install

node_exporter_user: node_exporter
node_exporter_version: 1.9.0
node_exporter_port: 9100
node_exporter_address: 0.0.0.0
node_exporter_full_name: "node_exporter-{{ node_exporter_version }}.linux-{{ host_arch }}"
node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/{{ node_exporter_full_name }}.tar.gz"

windows_exporter_version: 0.30.5
windows_exporter_full_name: windows_exporter-{{ windows_exporter_version }}-{{ host_arch }}
windows_exporter_port: 9100
windows_exporter_download_url: "https://github.com/prometheus-community/windows_exporter/releases/download/v{{ windows_exporter_version }}/{{ windows_exporter_full_name }}.msi"
windows_exporter_dest: "C:\\Users\\ansible\\{{ windows_exporter_full_name }}.msi"