# roles/node-exporter/defaults/main.yaml

node_exporter_user: node_exporter
node_exporter_version: 1.9.0
host_arch: amd64
node_exporter_port: 9100
node_exporter_address: 0.0.0.0
node_exporter_full_name: "node_exporter-{{ node_exporter_version }}.linux-{{ host_arch }}"
node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/{{ node_exporter_full_name }}.tar.gz"