# roles/node-exporter/tasks/main.yaml

- name: Test connection
  ping:

- name: Check if action is valid
  fail:
    msg: "Invalid action: {{ action }}. Valid values must be 'install' or 'uninstall'."
  when: action not in ['install', 'uninstall']

- name: Detect OS type
  set_fact:
    is_windows: "{{ ansible_os_family | lower == 'windows' }}"
    is_linux: "{{ ansible_os_family | lower in ['debian', 'redhat', 'ubuntu', 'linux'] }}"

# Условие для установки на Linux
- name: Include Linux installation tasks
  include_tasks: install_linux.yaml
  when:
    - action == "install"
    - is_linux

# Условие для установки на Windows
- name: Include Windows installation tasks
  include_tasks: install_windows.yaml
  when:
    - action == "install"
    - is_windows

# Условие для удаления на Linux
- name: Include Linux uninstallation tasks
  include_tasks: uninstall_linux.yaml
  when:
    - action == "uninstall"
    - is_linux

# Условие для удаления на Windows
- name: Include Windows uninstallation tasks
  include_tasks: uninstall_windows.yaml
  when:
    - action == "uninstall"
    - is_windows